name: Vercel Production Deploy

on:
  workflow_dispatch:

  push:
    branches:
      - main

  schedule:
    # 04:00 UTC = 01:00 Brasil (UTC-3)
    - cron: "0 4 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Deploy Hook
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"