name: Scheduled Vercel Production Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Production Deploy
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"